# Generated by Django 5.0.6 on 2024-10-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_price',
        ),
        migrations.AddField(
            model_name='item',
            name='image_price',
            field=models.IntegerField(default=55, max_length=10),
        ),
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.google.com/imgres?q=image%20holder%20icon&imgurl=https%3A%2F%2Fpng.pngtree.com%2Fpng-vector%2F20190223%2Fourmid%2Fpngtree-vector-picture-icon-png-image_695350.jpg&imgrefurl=https%3A%2F%2Fpngtree.com%2Fso%2Fimage-placeholder-icon&docid=izXt3Hg13MnDFM&tbnid=LMefkyX3ok017M&vet=12ahUKEwie2Pn32_mIAxXk0KACHdAFAE4QM3oECHoQAA..i&w=360&h=360&hcb=2&ved=2ahUKEwie2Pn32_mIAxXk0KACHdAFAE4QM3oECHoQAA', max_length=500),
        ),
    ]
